### ISSUE TITLE
Mark to update local files with GitHub repo

### ISSUE THREAD

**Issue by jcastle-zz** [GSA/open.gsa.gov.github.io#19]
Joe and Raed have Jekyll running localhost.  Need to get Mark's local files uploaded to the repo so we can sync the repo and start using pull functions.

**Comment by mvogelgesang** [comment]
@jcastle everything I have is posted to open.gsa.gov.github.io. Is there something specific you are looking for?

**Comment by jcastle-zz** [comment]
I was referring to the below text from your email to Raed last week.

Raed, this looks good. The Events and About tabs were added but it appears that I never updated the _config.yml file to include a tab for an APIs tab.

**Comment by mvogelgesang** [comment]
Ahh, update coming shortly!

**Comment by mvogelgesang** [comment]
@jcastle files updated on Master
